[colors]
foreground    = "#d4dadd"
background    = "#182024"
cursor_bg     = "#d4dadd"
cursor_border = "#d4dadd"
cursor_fg     = "#182024"
selection_bg  = "#434f56"
selection_fg  = "#d4dadd"
ansi = [
  "#2d3539", # black
  "#d19494", # red
  "#a6c982", # green
  "#d1b394", # yellow
  "#94a3d1", # blue
  "#bd94d1", # magenta
  "#94c7d1", # cyan
  "#8d9da5", # white
]
brights = [
  "#70868f",
  "#dd8888",
  "#b3dd88",
  "#d9c68c",
  "#889ddd",
  "#c188dd",
  "#90d5be",
  "#d4dadd"
]
